name: Setup
description: "Setup GAPROOT and dependencies"

runs:
  using: "composite"
  steps:

    - name: "Add custom GAP root"
      shell: bash
      run: ln -f -s $PWD /tmp/gaproot/pkg/

    - name:
      uses: gap-actions/install-pkg@v1
      with:
        packages: polycyclic@2.17
