coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 100%
        threshold: 5%
    patch: no
    changes: no

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
  - "*.g"
  - "lib/safemode.gi"
  - "lib/pcp/safemode_pcp.gi"
  - "tst/**"
  - "doc/**"
