coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: no
    patch:
      default:
        target: 100%
        threshold: 5%
        base: auto
    changes: no

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
  - "PackageInfo.g"
  - "init.g"
  - "read.g"
  - "tst/**"
  - "doc/**"
