language: c

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - zlib1g-dev
    - pari-gp

matrix:
  include:
    - env:
      - GAPBRANCH="master"
      - GAP_PKGS_TO_CLONE="polycyclic"
    - env:
      - GAPBRANCH="master"
      - GAP_PKGS_TO_CLONE="https://github.com/gap-packages/polycyclic/releases/download/v2.16/polycyclic-2.16.tar.gz"
    - env:
      - GAPBRANCH="stable-4.11"
      - GAP_PKGS_TO_CLONE="https://github.com/gap-packages/polycyclic/releases/download/v2.15.1/polycyclic-2.15.1.tar.gz"
    - env: 
      - GAPBRANCH="stable-4.10"
      - GAP_PKGS_TO_CLONE="https://github.com/gap-packages/polycyclic/releases/download/v2.14/polycyclic-2.14.tar.gz"

branches:
  only:
    - dev
    - master

before_script:
  - git clone https://github.com/gap-system/pkg-ci-scripts.git scripts
  - scripts/build_gap.sh

script:
  - scripts/build_pkg.sh && scripts/run_tests.sh

after_script:
  - scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
