name: TwistedConjugacy
version: "2.0.0"
license: "GPL-2.0-or-later"
date: 2021-05-01
description: |
    Computation with twisted conjugacy classes

authors:
    - name: Sam Tertooy
      url: https://stertooy.github.io/

maintainers:
    - name: Sam Tertooy
      url: https://stertooy.github.io/

GAP: ">= 4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.6.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

suggested-pkgs:
    - name: "AutoDoc"
      version: "2018.02.14"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "Polycyclic"
      version: "2.13.1"
      url: "https://gap-packages.github.io/polycyclic/"

www: https://sTertooy.github.io/TwistedConjugacy/
readme: README.md
packageinfo: https://sTertooy.github.io/TwistedConjugacy/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/sTertooy/TwistedConjugacy/releases/download/v2.0.0/TwistedConjugacy-2.0.0.tar.gz

abstract: |
    The TwistedConjugacy package provides methods to calculate Reidemeister classes, numbers, spectra and zeta functions, as well as coincidence groups of group homomorphisms. These methods are, for the most part, designed to be used with (group homomorphisms between) finite groups and, if the package polycyclic is also installed, polycyclically presented groups.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    coincidence group, fixed point group, Reidemeister number, Reidemeister spectrum, Reidemeister zeta function, twisted conjugacy.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Ter21</span>]   <b class='BibAuthor'>Tertooy, S.</b>,
     <i class='BibTitle'>TwistedConjugacy, Computation with twisted conjugacy classes,
             Version 2.0.0</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://sTertooy.github.io/TwistedConjugacy/">https://sTertooy.github.io/TwistedConjugacy/</a></span>.
    </p>
    

bibtex: |
    @misc{ TwistedConjugacy2.0.0,
      author =           {Tertooy, S.},
      title =            {{TwistedConjugacy}, Computation with twisted conjugacy
                          classes, {V}ersion 2.0.0},
      month =            {May},
      year =             {2021},
      note =             {GAP package},
      howpublished =     {\href   {https://sTertooy.github.io/TwistedConjugacy/}
                          {\texttt{https://sTertooy.github.io/}\discretionary
                          {}{}{}\texttt{TwistedConjugacy/}}},
      keywords =         {coincidence  group;  fixed  point  group; Reidemeister
                          number;   Reidemeister   spectrum;  Reidemeister  zeta
                          function; twisted conjugacy},
      printedkey =       {Ter21}
    }

