name: TwistedConjugacy
version: "2.2.0"
license: "GPL-2.0-or-later"
date: 2024-02-13
description: |
    Computation with twisted conjugacy classes

authors:
    - name: Sam Tertooy
      url: https://stertooy.github.io/

maintainers:
    - name: Sam Tertooy
      url: https://stertooy.github.io/

GAP: ">= 4.12"

suggested-pkgs:
    - name: "Polycyclic"
      version: "2.16"
      url: "https://gap-packages.github.io/polycyclic/"

www: https://stertooy.github.io/TwistedConjugacy
readme: README.md
packageinfo: https://stertooy.github.io/TwistedConjugacy/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/stertooy/TwistedConjugacy/releases/download/v2.2.0/TwistedConjugacy-2.2.0.tar.gz

abstract: |
    
        The TwistedConjugacy package provides methods to calculate Reidemeister
        classes, numbers, spectra and zeta functions, as well as other methods
        related to homomorphisms, endomorphisms and automorphisms of groups.
        These methods are, for the most part, designed to be used with finite
        groups and polycyclically presented groups.

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    coincidence group, endomorphism, fixed point group, homomorphism, Reidemeister number, Reidemeister spectrum, Reidemeister zeta function, twisted conjugacy.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Ter24</span>]   <b class='BibAuthor'>Tertooy, S.</b>,
     <i class='BibTitle'>TwistedConjugacy, Computation with twisted conjugacy classes,
             Version 2.2.0</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://stertooy.github.io/TwistedConjugacy">https://stertooy.github.io/TwistedConjugacy</a></span>.
    </p>
    

bibtex: |
    @misc{ TwistedConjugacy2.2.0,
      author =           {Tertooy, S.},
      title =            {{TwistedConjugacy}, Computation with twisted conjugacy
                          classes, {V}ersion 2.2.0},
      month =            {Feb},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href    {https://stertooy.github.io/TwistedConjugacy}
                          {\texttt{https://stertooy.github.io/}\discretionary
                          {}{}{}\texttt{TwistedConjugacy}}},
      keywords =         {coincidence  group;  endomorphism;  fixed point group;
                          homomorphism;    Reidemeister   number;   Reidemeister
                          spectrum;    Reidemeister   zeta   function;   twisted
                          conjugacy},
      printedkey =       {Ter24}
    }

