name: Test (GAP)
description: "Test GAP"
inputs:
  gap-version:
    type: string
  mode:
    default: 'default'
    type: string
  warnings-as-errors:
    default: true
    type: boolean
  complete:
    default: false
    type: boolean

runs:
  using: "composite"
  steps:

    - name: "Add custom GAP root"
      uses: ./.github/actions/setup
      with:
        gap-version: ${{ inputs.gap-version }}
        mode: ${{ inputs.mode }}

    - name: "Run GAP tests"
      uses: stertooy/run-gap-tests@v1
      with:
        complete: ${{ inputs.complete }}
        mode: ${{ inputs.mode }}
        warnings-as-errors: ${{ inputs.warnings-as-errors }}
