name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: GAP ${{ matrix.gap-branch }}
    runs-on: ubuntu-latest
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    strategy:
      fail-fast: false
      matrix:
        include: 
          - gap-branch: master
            packages-to-clone: 'alnuth autpgrp polycyclic'
          - gap-branch: stable-4.11
            no-coverage: true
          - gap-branch: stable-4.10
            no-coverage: true
          - gap-branch: stable-4.9
            no-coverage: true

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install PARI/GP'
        run: |
          sudo apt-get update
          sudo apt-get install pari-gp
      - name: 'Setup GAP'
        uses: sTertooy/setup-gap@v3
        with:
          GAP_PKGS_TO_CLONE: ${{ matrix.packages-to-clone }}
          GAPBRANCH: ${{ matrix.gap-branch }}
      - name: 'Add package to GAP'
        uses: gap-actions/build-pkg@v1
      - name: 'Run tests with default packages'
        uses: sTertooy/run-pkg-tests@v3
        with:
          GAP_TESTFILE: 'tst/teststandard.g'
          GAP_FLAGS: '-b'
          NO_COVERAGE: ${{ matrix.no-coverage }}
      - name: 'Run tests with necessary packages'
        uses: sTertooy/run-pkg-tests@v3
        with:
          GAP_TESTFILE: 'tst/testonlyneeded.g'
          GAP_FLAGS: '-b -r -A'
          NO_COVERAGE: ${{ matrix.no-coverage }}
      - name: 'Run tests with all packages'
        uses: sTertooy/run-pkg-tests@v3
        with:
          GAP_TESTFILE: 'tst/testallpackages.g'
          GAP_FLAGS: '-b'
          NO_COVERAGE: ${{ matrix.no-coverage }}
      - name: 'Process coverage'
        uses: gap-actions/process-coverage@v2
        if: ${{ !matrix.no-coverage }}
      - name: 'Upload coverage'
        if: ${{ !matrix.no-coverage }}
        run: bash <(curl -s https://codecov.io/bash)
        shell: bash

  manual:
    name: Manual
    runs-on: ubuntu-latest
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup GAP'
        uses: gap-actions/setup-gap@v2
      - name: 'Build documentation'
        uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'
      - name: 'Upload documentation'
        uses: actions/upload-artifact@v2
        with:
          name: manual
          path: ./doc/manual.pdf