name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: GAP ${{ matrix.gap-branch }}
    runs-on: ubuntu-latest
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    strategy:
      fail-fast: false
      matrix:
        include: 
          - gap-branch: master
            gap-pkgs-to-clone: 'alnuth autpgrp polycyclic'
          - gap-branch: stable-4.11
          - gap-branch: stable-4.10
          - gap-branch: stable-4.9

    steps:
      - uses: actions/checkout@v2
      - name: 'Install PARI/GP'
        run: |
          sudo apt-get update
          sudo apt-get install pari-gp
      - uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_CLONE: ${{ matrix.gap-pkgs-to-clone }}
          GAPBRANCH: ${{ matrix.gap-branch }}
      - uses: gap-actions/build-pkg@v1
      - uses: gap-actions/run-pkg-tests@v2
        with:
          GAP_TESTFILE: 'tst/teststandard.g'
      - uses: gap-actions/process-coverage@v1

  manual:
    name: Manual
    runs-on: ubuntu-latest
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap@v2
      - uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'
      - name: 'Upload documentation'
        uses: actions/upload-artifact@v2
        with:
          name: manual
          path: ./doc/manual.pdf