name: Lint
on:
  - workflow_dispatch

jobs:
  lint:
    name: ${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter:
          - gaplint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Install gaplint
        run: pip install gaplint
      - name: Run linter
        run: |
          shopt -s globstar
          FOLDERS="lib/** **/*.g"
          gaplint $FOLDERS
          # Also check for double semicolon
          blah=$(egrep -ir --include=*.{g,gi,gd} ";;" $FOLDERS)
          if [[ ! $blah ]]; then exit 0; else exit 1; fi
