name: Lint
on:
  - workflow_dispatch

jobs:
  lint:
    name: "Test code quality"
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name 

    steps:
    
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5

      - name: Install gaplint
        run: pip install gaplint

      - name: Run linter
        run: |
          shopt -s globstar
          FOLDERS="lib/** **/*.g"
          gaplint $FOLDERS
          # Also check for double semicolon
          blah=$(egrep -ir --include=*.{g,gi,gd} ";;" lib/** **/*.g | tee /dev/stderr)
          if [[ ! $blah ]]; then exit 0; else exit 1; fi
