name: Lint
on:
  - push
  - pull_request
  - workflow_call
  - workflow_dispatch

jobs:

  lint:
    name: "Run gaplint"
    runs-on: ubuntu-slim
    strategy:
      fail-fast: false
      matrix:
        include:
          - files: "*.g !(doc|examples)/**/*.g*"
            disable: "W003,W004,W012,W013,W014"
          - files: "examples/**/*.g*"
            disable: "W003,W004,W012,W013,W014,W049"

    steps:
    
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup Python"
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: "Install gaplint"
        shell: bash
        run: pip install gaplint

      - name: "Run gaplint"
        shell: bash
        run: |
          shopt -s globstar extglob
          FILES="${{ matrix.files }}"
          OPTS="--columns=79 --indentation=4 --disable=${{ matrix.disable }}"
          gaplint $FILES $OPTS
