name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Only create an archive containing the release instead of publishing it on GitHub"
        type: boolean
        required: false
        default: false
      force:
        description: "Allow overwriting an existing release, or making a release with an incorrect date"
        type: boolean
        required: false
        default: false

permissions: write-all

jobs:
  release:
    name: "Release the GAP package"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: gap-actions/setup-gap@v3
      - uses: gap-actions/build-pkg-docs@v2
        with:
          use-latex: true
      - run: |
          {
            echo 'BODY<<EOF'
            sed -n '/^[0-9]\+\.[0-9]\+\.[0-9]\+/{:a;n;/^[0-9]\+\.[0-9]\+\.[0-9]\+/q;/^[-]\+$/ba;/^-/p;ba}' CHANGES.md
            echo EOF
          } >> $GITHUB_ENV
      - run: |
          echo "$BODY"
      - uses: gap-actions/release-pkg@v1
        with:
          dry-run: ${{ inputs.dry-run }}
          body-text: ${{ env.BODY }} 
          force: ${{ inputs.force }}
      - uses: gap-actions/update-gh-pages@v1
        if: ${{ !inputs.dry-run }}
