name: Setup
on:
  - workflow_call

jobs:

  setup:
    name: "Setup package, gaproot, polycyclic"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Add custom GAP root"
        run: ln -f -s $PWD /tmp/gaproot/pkg/

      - name: "Install Polycyclic 2.17 if necessary"
        run: |
          gap -A << GAPInput
            pkg := "polycyclic";
            ver := "2.17";
            if TestPackageAvailability( pkg, ver, true ) = fail then
              LoadPackage( "PackageManager" : OnlyNeeded );
              QuitGap( InstallPackage( pkg, Concatenation( "=", ver ) ) );
            fi;
            QUIT;
          GAPInput
