name: testpackagesload

on:
  - workflow_dispatch

jobs:
  packagesload:
    name: "GAP-${{ matrix.gap-branch }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - gap-branch: "master"
            packages: "alnuth autpgrp polycyclic"
          - gap-branch: "4.11"
          - gap-branch: "4.10"
          - gap-branch: "4.9"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Add package to GAP"
        uses: sTertooy/GAD-extra-packages@v0.1
        with:
          PACKAGES: ${{ matrix.packages }}
      - name: "Add package to GAP"
        uses: sTertooy/GDA-build-package@v0.3
      - name: "Add package to GAP"
        uses: sTertooy/GDA-test-load@v0.1
      - name: "Upload output"
        uses: actions/upload-artifact@v3
        with:
          name: "testpackagesload-${{ matrix.gap-branch }}"
          path: /opt/gap/dev/log/*
          if-no-files-found: error
