name: teststandard

on:
  - workflow_dispatch

jobs:
  test:
    name: GAP ${{ matrix.gap-branch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - gap-branch: master
            packages-to-clone: 'alnuth autpgrp polycyclic'
          - gap-branch: stable-4.11
          # stable-4.10 or older will take ~3 hours each, not recommended

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup GAP'
        uses: sTertooy/setup-gap@v4
        with:
          GAP_PKGS_TO_CLONE: ${{ matrix.packages-to-clone }}
          GAPBRANCH: ${{ matrix.gap-branch }}
      - name: 'Add package to GAP'
        uses: sTertooy/build-pkg@v2
      - name: 'Run teststandard.g with only necessary packages loaded'
        uses: sTertooy/pkg-install-test@v1
        with:
          COMPLETE: true
          ONLY_NEEDED: true
      - name: 'Run teststandard.g with suggested packages loaded'
        uses: sTertooy/pkg-install-test@v1
        with:
          COMPLETE: true