name: testpackagesload

on:
  - workflow_dispatch

jobs:
  test:
    name: GAP ${{ matrix.gap-branch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - gap-branch: master
            packages-to-clone: 'alnuth autpgrp polycyclic'
          - gap-branch: stable-4.11
          - gap-branch: stable-4.10
          - gap-branch: stable-4.9

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup GAP'
        uses: sTertooy/setup-gap@v4
        with:
          GAP_PKGS_TO_CLONE: ${{ matrix.packages-to-clone }}
          GAPBRANCH: ${{ matrix.gap-branch }}
      - name: 'Add package to GAP'
        uses: sTertooy/build-pkg@v2
      - name: 'Test package loading'
        uses: sTertooy/pkg-load-test@v2
      - name: 'Upload output'
        uses: actions/upload-artifact@v2
        with:
          name: testpackagesload-${{ matrix.gap-branch }}
          path: ~/gap/dev/log/*
          if-no-files-found: error
