name: Run package compatibility tests

on:
  - workflow_call
  - workflow_dispatch

jobs:
  test:
    name: "Test ${{ matrix.test-suite }} (version: ${{ matrix.gap-version }}, mode: loadall)"
    uses: ./.github/workflows/test.yml
    with:
      test-suite: ${{ matrix.test-suite }}
      gap-version: ${{ matrix.gap-version }}
      mode: 'loadall'
      coverage: false
      complete: false
      warnings-as-errors: false
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-suite: [ "package", "GAP" ]
        gap-version: [ "4.14.0", "4.15.0", "4.15.1", "master" ]

  test-additional:
    name: "Additional tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    container:
      image: ghcr.io/stertooy/gda-image:master-slim

    steps:

      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Add custom GAP root"
        run: ln -f -s $PWD /tmp/gaproot/pkg/

      - name: "Verify that tests do not depend on PrimGrp/SmallGrp/TransGrp"
        shell: bash
        run: gap --bare -c 'LoadPackage("GAPDoc");LoadPackage("Polycyclic");TestPackage("TwistedConjugacy");'

      - name: "Verify that we do not interfere with Polycyclic's tests"
        shell: bash
        run: gap -A -c 'LoadPackage("Polycyclic");LoadPackage("TwistedConjugacy");TestPackage("Polycyclic");'
