name: "Test GAP installation (complete)"

on:
  - workflow_dispatch

jobs:
  test:
    name: "Test on GAP-${{ matrix.gap-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - gap-version: "master"
          - gap-version: "4.14.0"

    container:
      image: ghcr.io/stertooy/gda-image:${{ matrix.gap-version }}-slim

    steps:

      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Run GAP tests with necessary packages"
        uses: sTertooy/gda-test-gap@v1
        with:
          COMPLETE: true
          ONLY_NEEDED: true

      - name: "Run GAP tests with suggested packages"
        uses: sTertooy/gda-test-gap@v1
        with:
          COMPLETE: true
