name: "Test compatibility with other GAP packages (complete)"

on:
  - workflow_dispatch

jobs:
  test:
    name: "Test on GAP-${{ matrix.gap-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - gap-version: "master"
          - gap-version: "4.14.0"

    container:
      image: ghcr.io/stertooy/gda-image:${{ matrix.gap-version }}-full

    steps:

      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Run GAP tests with all packages"
        uses: sTertooy/gda-test-gap@v1
        with:
          COMPLETE: true
          ALL_PACKAGES: true

      - name: "Run package tests with all packages"
        uses: sTertooy/gda-test-pkg@v1
        with:
          ALL_PACKAGES: true
