name: testpackagesload

on:
  - workflow_dispatch

jobs:
  test:
    name: GAP ${{ matrix.gap-branch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: 
          - gap-branch: master
            packages-to-clone: 'alnuth autpgrp polycyclic'
          - gap-branch: stable-4.11
            no-coverage: true
          - gap-branch: stable-4.10
            no-coverage: true
          - gap-branch: stable-4.9
            no-coverage: true
			
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup GAP'
        uses: gap-actions/setup-gap@v2
      - name: 'Add package to GAP'
        uses: gap-actions/build-pkg@v1
      - name: 'Make packagesload'
        uses: sTertooy/pkg-load-test@v1
