name: testpackagesload

on:
  - workflow_dispatch

jobs:
  test:
    name: GAP ${{ matrix.gap-branch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: 
          - gap-branch: master
          - gap-branch: stable-4.11
          - gap-branch: stable-4.10
          - gap-branch: stable-4.9

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup GAP'
        uses: gap-actions/setup-gap@v2
      - name: 'Add package to GAP'
        uses: gap-actions/build-pkg@v1
      - name: 'Test package loading'
        uses: sTertooy/pkg-load-test@v1
      - name: 'Upload output'
        uses: actions/upload-artifact@v2
        with:
          name: testpackagesload-logs-${{ matrix.gap-branch }}
          path: ~/gap/dev/log/*
          if-no-files-found: error