name: teststandard

on:
  - workflow_dispatch

jobs:
  test:
    name: GAP ${{ matrix.gap-branch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: 
          - gap-branch: master
            packages-to-clone: 'alnuth autpgrp polycyclic'
          - gap-branch: stable-4.11

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup GAP'
        uses: sTertooy/setup-gap@v3
        with:
          GAP_PKGS_TO_CLONE: ${{ matrix.packages-to-clone }}
          GAPBRANCH: ${{ matrix.gap-branch }}
      - name: 'Add package to GAP'
        uses: gap-actions/build-pkg@v1
      - name: 'Run teststandard.g with necessary packages'
        uses: sTertooy/pkg-install-test@v0.8
        with:
          COMPLETE: true
      - name: 'Run teststandard.g with only needed packages'
        uses: sTertooy/pkg-install-test@v0.8
        with:
          COMPLETE: true
          ONLY_NEEDED: true