name: "Run GAP tests"

on:
  - workflow_dispatch

jobs:
  test:
    name: "Test on GAP-${{ matrix.gap-version }} (mode = ${{ matrix.mode }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-version: [ "master", "4.15.0-beta2", "4.14.0" ]
        mode: [ "default", "onlyneeded" ]

    container:
      image: ghcr.io/stertooy/gda-image:${{ matrix.gap-version }}-slim

    steps:

      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Add custom GAP root"
        run: ln -f -s $PWD /tmp/gaproot/pkg/

      - name: "Install Polycyclic 2.17 if necessary"
        if: ${{ matrix.mode == 'default' }}
        shell: bash
        run: |
          gap -A << GAPInput
            if LoadPackage("polycyclic","2.17") <> true then
              LoadPackage("PackageManager":OnlyNeeded);
              QuitGap(InstallPackage("polycyclic","=2.17"));
            fi;
            QUIT;
          GAPInput
          gap -A -c 'QuitGap(LoadPackage("polycyclic","2.17"));'

      - name: "Run GAP tests"
        uses: stertooy/run-gap-tests@v1
        with:
          complete: true
          warnings-as-errors: true
          mode: ${{ matrix.mode }}
