name: "Run GAP tests"

on:
  - workflow_dispatch

jobs:
  test:
    name: "Test GAP extensively (version: ${{ matrix.gap-version }}, mode: ${{ matrix.mode }})"
    uses: ./.github/workflows/test.yml
    with:
      test-suite: "GAP"
      gap-version: ${{ matrix.gap-version }}
      mode: ${{ matrix.mode }}
      coverage: false
      complete: true
      warnings-as-errors: true
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        mode: [ "default", "onlyneeded" ]
        gap-version: [ "4.14.0", "4.15.0", "4.15.1", "master" ]
