name: Validate
on:
  - workflow_call
  - workflow_dispatch

jobs:

  validate:
    name: "Validate"
    runs-on: ubuntu-latest

    steps:
    
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Validate CITATION.cff"
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--validate"
